# Site settings
title: codepitbull
author: Jochen Mader
email: blog@codepitbull.de
header-img: img/home-bg.jpg
description: "Ramblings, Thoughts and Notes about Software Engineering."
baseurl: ""
url: "http://codepitbull.de"
twitter_username: codepitbull
github_username:  codepitbull
xing_username: Jochen_Mader
linkedin_username: jochen-mader-a4b965112
slideshare_username: codepitbull 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
gems: [jekyll-paginate]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins:
  - jekyll-archives
#theme: moving
emote_theme: huangyz0918/moving
show_excerpts: true
moving:
  avatar_url: "/img/jochen.png" # avatar in about page
  about_you: Coder/Speaker/Writer.
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.
  social_links:
    rss: RSS
    github:  codepitbull
    twitter: codepitbull