baseURL = "https://codepitbull.de/"
title = "codepitbull"

theme = "puppet"
themesDir = "themes"

copyright = "Copyright © Jochen Mader 2024 <a href = \"/imprint\">Impressum</a>"
paginate = 3
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "videos"
name = "Videos"
url = "/video/"
weight = 10
[[menu.main]]
identifier = "print"
name = "Print"
url = "/print/"
weight = 20
[[menu.main]]
identifier = "talks"
name = "Talks"
url = "/talks/"
weight = 30
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/codepitbull"
weight = 100


[params]
author = "codepitbull"
description = "An aggregator for all the things I do"
keywords = "blog,developer,personal"
img_home = "img/road_bg.jpg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/jochen.png"
bio = "family/veganism/music/code"

[params.social]
twitter = "codepitbull"
github = "codepitbull"
linkedin = "https://www.linkedin.com/in/jochen-mader-a4b965112/"
rss = true
[params.social.mastodon]
weight = 56
icon = "fab fa-mastodon"
format = "https://chaos.social/%v"
id = "@codepitbull"
url = ""
[params.social.bluesky]
weight = 66
icon = "fab fa-mastodon"
format = "https://bsky.app/profile/%v"
id = "codepitbull.bsky.social"
url = "https://bsky.app/profile/codepitbull.bsky.social"
